"""
GUS v7 — Phase 42
Decision Schema Lock (v0.1)

STRICT:
- No execution logic
- No inference
- Lock artifact only
- Deterministic / fail-closed ready
"""

from gus_v7.decision_integrity.decision_integrity_schema_v0_1 import (
    DECISION_KEYS,
    VALID_DECISION_OUTPUTS,
    VALID_INTEGRITY_STATUS_VALUES,
    REQUIRED_NON_EMPTY_FIELDS,
    NO_EXTRA_FIELDS_ALLOWED,
    IMMUTABLE_AFTER_CREATION,
    VALIDATION_RULES,
    FAIL_CLOSED_BEHAVIOR,
)


# =========================
# AUTHORITY SOURCE LOCK
# =========================

CANONICAL_DECISION_SCHEMA_MODULE = (
    "gus_v7.decision_integrity.decision_integrity_schema_v0_1"
)


# =========================
# CANONICAL BINDINGS
# =========================

LOCKED_DECISION_KEYS = DECISION_KEYS

LOCKED_VALID_DECISION_OUTPUTS = VALID_DECISION_OUTPUTS

LOCKED_VALID_INTEGRITY_STATUS_VALUES = VALID_INTEGRITY_STATUS_VALUES

LOCKED_REQUIRED_NON_EMPTY_FIELDS = REQUIRED_NON_EMPTY_FIELDS

LOCKED_NO_EXTRA_FIELDS_ALLOWED = NO_EXTRA_FIELDS_ALLOWED

LOCKED_IMMUTABLE_AFTER_CREATION = IMMUTABLE_AFTER_CREATION

LOCKED_VALIDATION_RULES = VALIDATION_RULES

LOCKED_FAIL_CLOSED_BEHAVIOR = FAIL_CLOSED_BEHAVIOR


# =========================
# DRIFT PROHIBITION
# =========================

PARALLEL_SCHEMA_DEFINITIONS_FORBIDDEN = True

SCHEMA_FIELD_DRIFT_FORBIDDEN = True

SCHEMA_OUTPUT_DRIFT_FORBIDDEN = True

SCHEMA_STATUS_DRIFT_FORBIDDEN = True


# =========================
# LOCK RULE IDS
# =========================

LOCK_RULES = (
    "DSL1_AUTHORITY_SOURCE_LOCK",
    "DSL2_FIELD_BINDING_LOCK",
    "DSL3_OUTPUT_BINDING_LOCK",
    "DSL4_STATUS_BINDING_LOCK",
    "DSL5_NO_PARALLEL_SCHEMA_LOCK",
    "DSL6_FAIL_CLOSED_BINDING_LOCK",
)


# =========================
# FAIL-CLOSED DEFINITION
# =========================

FAIL_CLOSED_LOCK_BEHAVIOR = "ANY_SCHEMA_MISMATCH_RESULTS_IN_LOCK_FAILURE"
